version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  frontend:
    build: ./Frontend/fp-group1/
    image: shamrehman/appfrontend
    ports:
    - target: 3000
      published: 3000
      protocol: tcp
    deploy:
      replicas: 3
  backend:
    build: ./Backend/
    image: shamrehman/appbackend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    deploy:
      replicas: 3
    environment: 
      DATABASE_URI: ${DATABASE_URI}
      DB_PW: ${DB_PW}
      SECRET_KEY: ${SECRET_KEY}
